### ISSUE TITLE
Make 'designdocs.md' accessible

### ISSUE THREAD

**Issue by mapachurro** [filecoin-project/designdocs#2]
I was browsing the new repos, and wanted to learn about the design docs -- the link in the readme comes up as a 404 for me:

https://github.com/filecoin-project/designdocs-internal/blob/master/designdocs.md

Not sure if this is a document that just needs to be made public, or what. 

Thanks!

**Comment by anorth** [comment]
Thanks for the report. We have a bunch of design docs to make public and fixing this link will probably come as part of that.

**Comment by mishmosh** [comment]
@mapachurro This should be fixed now, thanks for the report.

https://github.com/filecoin-project/designdocs/blob/master/designdocs.md
